name: Build check

on:
  push:
    branches: [ develop ]
  pull_request:
    branches: [ develop ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: set up JDK 17
      uses: actions/setup-java@v2
      with:
        java-version: '17'
        distribution: 'adopt'
        cache: gradle

    - name: Grant execute permission for gradlew
      run: chmod +x gradlew
    - name: Build module Video-Common-UI
      run: ./gradlew :video-common-ui:build
    - name: Build module Video-SDK
      run: ./gradlew :video-sdk:build
    - name: Build module Video-Glasses-SDK
      run: ./gradlew :video-glasses-sdk:build
    - name: Build App
      run: ./gradlew :app:build
