name: Build check

on:
  workflow_dispatch:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main      

jobs:
  
  determine-runner-integration:
    name: Determine which runner to use for integration tests
    runs-on: ubuntu-latest
    outputs:
      runner: ${{ steps.set-runner.outputs.runner }}
    steps:
      - name: Generate a token
        id: generate_token
        uses: actions/create-github-app-token@v1
        with:
          app-id: ${{ secrets.APP_ID }}
          private-key: ${{ secrets.APP_PRIVATE_KEY }}
      - name: Determine which runner to use
        id: set-runner
        uses: benjaminmichaelis/get-soonest-available-runner@v1.1.0
        with:
          primary-runner: "self-hosted"
          fallback-runner: "ubuntu-latest"
          # This correlates to the number of free runners that must exist when the API queries.
          # Increasing this can help in case you have lots of actions querying at the same time for a race condition between the time you query the runner and when the runner actually takes the job it will execute.
          min-available-runners: 2
          github-token: ${{steps.generate_token.outputs.token}}
  
  build_common:
    needs: determine-runner-integration
    runs-on: ${{ needs.determine-runner-integration.outputs.runner }}
    steps:
      - uses: actions/checkout@v2
      - name: set up JDK 17
        uses: actions/setup-java@v2
        with:
          java-version: '17'
          distribution: 'adopt'
          cache: gradle
      - name: add python dependency
        run: python3 -m pip install semver boto3
      - name: Grant execute permission for gradlew
        run: chmod +x gradlew
      - name: Build module Video-Common-UI
        run: ./gradlew :video-common-ui:build

  build_video_sdk:
    runs-on: ${{ needs.determine-runner-integration.outputs.runner }}
    needs: build_common
    steps:
      - uses: actions/checkout@v2
      - name: set up JDK 17
        uses: actions/setup-java@v2
        with:
          java-version: '17'
          distribution: 'adopt'
          cache: gradle
      - name: add python dependency
        run: python3 -m pip install semver boto3
      - name: Grant execute permission for gradlew
        run: chmod +x gradlew
      - name: Build module Video-SDK
        run: ./gradlew :video-sdk:build

  build_glasses_sdk:
    runs-on: ${{ needs.determine-runner-integration.outputs.runner }}
    needs: build_common
    steps:
      - uses: actions/checkout@v2
      - name: set up JDK 17
        uses: actions/setup-java@v2
        with:
          java-version: '17'
          distribution: 'adopt'
          cache: gradle
      - name: add python dependency
        run: python3 -m pip install semver boto3
      - name: Grant execute permission for gradlew
        run: chmod +x gradlew
      - name: Build module Video-Glasses-SDK
        run: ./gradlew :video-glasses-sdk:build

  build_app:
    runs-on: ${{ needs.determine-runner-integration.outputs.runner }}
    needs: [ build_video_sdk, build_glasses_sdk ]
    steps:
      - uses: actions/checkout@v2
      - name: set up JDK 17
        uses: actions/setup-java@v2
        with:
          java-version: '17'
          distribution: 'adopt'
          cache: gradle
      - name: add python dependency
        run: python3 -m pip install semver boto3
      - name: Grant execute permission for gradlew
        run: chmod +x gradlew
      - name: Decode Keystore
        id: decode_keystore
        env:
          ENCODED_STRING: ${{ secrets.KEYSTORE }}
        run: echo $ENCODED_STRING | base64 -di > app/keystores/release.keystore
      - name: Build module App
        run: ./gradlew :app:build
        env:
          SIGNING_KEY_ALIAS: ${{ secrets.SIGNING_KEY_ALIAS }}
          SIGNING_KEY_PASSWORD: ${{ secrets.SIGNING_KEY_PASSWORD }}
          SIGNING_STORE_PASSWORD: ${{ secrets.SIGNING_STORE_PASSWORD }}

    
