name: Build check

on:
  workflow_dispatch:
  push:
   branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build_common:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: set up JDK 17
        uses: actions/setup-java@v2
        with:
          java-version: '17'
          distribution: 'adopt'
          cache: gradle
      - name: add python dependency
        run: python3 -m pip install semver boto3
      - name: Grant execute permission for gradlew
        run: chmod +x gradlew
      - name: Build module Video-Common-UI
        run: ./gradlew :video-common-ui:testDebugUnitTest

  build_video_sdk:
    runs-on: ubuntu-latest
    needs: build_common
    steps:
      - uses: actions/checkout@v2
      - name: set up JDK 17
        uses: actions/setup-java@v2
        with:
          java-version: '17'
          distribution: 'adopt'
          cache: gradle
      - name: add python dependency
        run: python3 -m pip install semver boto3
      - name: Grant execute permission for gradlew
        run: chmod +x gradlew
      - name: Build module Video-SDK
        run: ./gradlew :video-sdk:testDebugUnitTest

  build_glasses_sdk:
    runs-on: ubuntu-latest
    needs: build_common
    steps:
      - uses: actions/checkout@v2
      - name: set up JDK 17
        uses: actions/setup-java@v2
        with:
          java-version: '17'
          distribution: 'adopt'
          cache: gradle
      - name: add python dependency
        run: python3 -m pip install semver boto3
      - name: Grant execute permission for gradlew
        run: chmod +x gradlew
      - name: Build module Video-Glasses-SDK
        run: ./gradlew :video-glasses-sdk:testDebugUnitTest

  build_app:
    runs-on: ubuntu-latest
    needs: [ build_video_sdk, build_glasses_sdk ]
    steps:
      - uses: actions/checkout@v2
      - name: set up JDK 17
        uses: actions/setup-java@v2
        with:
          java-version: '17'
          distribution: 'adopt'
          cache: gradle
      - name: add python dependency
        run: python3 -m pip install semver boto3
      - name: Grant execute permission for gradlew
        run: chmod +x gradlew
      - name: Decode Keystore
        id: decode_keystore
        env:
          ENCODED_STRING: ${{ secrets.KEYSTORE }}
        run: echo $ENCODED_STRING | base64 -di > app/keystores/release.keystore
      - name: Build module App
        run: ./gradlew :app:build
        env:
          SIGNING_KEY_ALIAS: ${{ secrets.SIGNING_KEY_ALIAS }}
          SIGNING_KEY_PASSWORD: ${{ secrets.SIGNING_KEY_PASSWORD }}
          SIGNING_STORE_PASSWORD: ${{ secrets.SIGNING_STORE_PASSWORD }}

    
