name: Release app on stores

on:
  workflow_dispatch:
    inputs:
      tag:
        description: Define the tag
        type: string
        required: true
  workflow_call:
    inputs:
      tag:
        description: Define the tag
        type: string
        required: true
jobs:
  build_aab:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          ref: ${{ github.event.inputs.tag }}
      - name: set up JDK 17
        uses: actions/setup-java@v4
        with:
          java-version: '17'
          distribution: 'adopt'
          cache: 'gradle'
      - name: Setup Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.10'
          cache: 'pip'
      - name: Install python deps
        run: pip install -r requirements.txt
      - name: Grant execute permission for gradlew
        run: chmod +x gradlew
      - name: Decode Keystore
        id: decode_keystore
        env:
          ENCODED_STRING: ${{ secrets.KEYSTORE }}
        run: echo $ENCODED_STRING | base64 -di > app/keystores/release.keystore
      - name: Build app bundle release (AAB)
        run: ./gradlew :app:bundleRelease
        env:
          SIGNING_KEY_ALIAS: ${{ secrets.SIGNING_KEY_ALIAS }}
          SIGNING_KEY_PASSWORD: ${{ secrets.SIGNING_KEY_PASSWORD }}
          SIGNING_STORE_PASSWORD: ${{ secrets.SIGNING_STORE_PASSWORD }}
      - name: Upload aab
        uses: actions/upload-artifact@v4
        with:
          name: build_release
          path: |
            app/build/outputs/bundle/release/app-release.aab
            app/build/outputs/mapping/release/mapping.txt
            app/build/intermediates/merged_native_libs/release/out/lib
  upload_playstore:
    runs-on: ubuntu-latest
    needs: build_aab
    steps:
      - uses: actions/checkout@v4
        with:
          ref: ${{ github.event.inputs.tag }}
      - name: Download math result for job 1
        uses: actions/download-artifact@v4
        with:
          name: build_release
          path: build
      - name: Deploy to PlayStore
        uses: r0adkll/upload-google-play@v1
        with:
          serviceAccountJsonPlainText: ${{ secrets.GOOGLE_SERVICE_ACCOUNT_JSON }}
          packageName: com.kaleyra.demo_video_sdk
          releaseFiles: build/outputs/bundle/release/app-release.aab
          track: beta
          mappingFile: build/outputs/mapping/release/mapping.txt
          debugSymbols: build/intermediates/merged_native_libs/release/out/lib
  upload_huawei:
    runs-on: ubuntu-latest
    needs: build_aab
    steps:
      - uses: actions/checkout@v4
        with:
          ref: ${{ github.event.inputs.tag }}
      - name: Download math result for job 1
        uses: actions/download-artifact@v4
        with:
          name: build_release
          path: build
      - name: Deploy to Huawei App Gallery
        uses: muhamedzeema/appgallery-deply-action@main
        with:
          client-id: ${{secrets.HUAWEI_CLIENT_ID}}
          client-key: ${{secrets.HUAWEI_CLIENT_KEY}}
          app-id: ${{secrets.HUAWEI_APP_ID}}
          file-extension: "aab"
          file-path: "build/outputs/bundle/release/app-release.aab"
          submit: false
