name: Release new SDK version

on:
  workflow_dispatch:
    inputs:
      specific_release_version:
        description: Define the specific release version?
        required: false
      release_version:
        type: choice
        description: What kind of release do you want to do?
        required: false
        options:
          - patch
          - minor
          - major

jobs:
  
  determine-runner-integration:
    name: Determine which runner to use for integration tests
    runs-on: ubuntu-latest
    outputs:
      runner: ${{ steps.set-runner.outputs.runner }}
    steps:
      - name: Generate a token
        id: generate_token
        uses: actions/create-github-app-token@v1
        with:
          app-id: ${{ secrets.APP_ID }}
          private-key: ${{ secrets.APP_PRIVATE_KEY }}
      - name: Determine which runner to use
        id: set-runner
        uses: benjaminmichaelis/get-soonest-available-runner@v1.1.0
        with:
          primary-runner: "self-hosted"
          fallback-runner: "ubuntu-latest"
          min-available-runners: 1
          github-token: ${{steps.generate_token.outputs.token}}

  update_sdk_version:
    needs: determine-runner-integration
    runs-on: ${{ needs.determine-runner-integration.outputs.runner }}
    outputs:
      tag: ${{ steps.output_tag.outputs.TAG }}
    steps:
      - name: Generate a token
        id: generate_token
        uses: actions/create-github-app-token@v1
        with:
          app-id: ${{ secrets.APP_ID }}
          private-key: ${{ secrets.APP_PRIVATE_KEY }}
      - uses: actions/checkout@v4
        with:
          token: ${{steps.generate_token.outputs.token}}
      - name: set up JDK 17
        uses: actions/setup-java@v4
        with:
          java-version: '17'
          distribution: 'adopt'
          cache: 'gradle'
      - name: Setup Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.10'
          cache: 'pip'
      - name: Install python deps
        run: pip install -r requirements.txt
      - name: Update Maven credentials
        env:
          MAVEN_ACCESSKEY: ${{ secrets.MAVEN_ACCESSKEY }}
          MAVEN_SECRETKEY: ${{ secrets.MAVEN_SECRETKEY }}
          MAVEN_DISTRIBUTIONID: ${{ secrets.MAVEN_DISTRIBUTIONID }}
        run:
          echo -e "maven.accessKey=$MAVEN_ACCESSKEY\nmaven.secretKey=$MAVEN_SECRETKEY\nmaven.distributionId=$MAVEN_DISTRIBUTIONID" >> ./local.properties
      - name: Generate documentation
        run: ./gradlew dokkaHtmlMultiModule
      - name: Update sdk version
        id: output_tag
        run: ./gradlew updateSdkVersion -PnewVersion=${{ inputs.specific_release_version || inputs.release_version }}
      - name: Release new common ui version
        run: ./gradlew :video-common-ui:publishUpload -PdryRun=false
      - name: Release new glasses sdk version
        run: ./gradlew :video-glasses-sdk:publishUpload -PdryRun=false
      - name: Release new sdk version
        run: ./gradlew :video-sdk:publishUpload -PdryRun=false
      - name: Update app version
        run: ./gradlew autoIncrementVersionCode
      - name: Update app sdk dependency
        run:
          sed -i 's/kaleyraVideoSdkVersion = "[0-9]*\.[0-9]*\.[0-9]*-*\w*"/kaleyraVideoSdkVersion = "'${{ inputs.specific_release_version || steps.output_tag.outputs.NEW_VERSION }}'"/g' ./app/build.gradle
      - uses: stefanzweifel/git-auto-commit-action@v5
        with:
          commit_message: "chore: Update sdk version"
          tagging_message: ${{ steps.output_tag.outputs.TAG }}

  update_bom_version:
    needs: [ determine-runner-integration, update_sdk_version ]
    runs-on: ${{ needs.determine-runner-integration.outputs.runner }}
    uses: KaleyraVideo/AndroidDependenciesCatalog/.github/workflows/release_bom.yml@main
    with:
      release_version: ${{ inputs.release_version }}
      specific_release_version: ${{ inputs.specific_release_version }}
    secrets: inherit

  release_apps:
    needs: [ determine-runner-integration, update_sdk_version, update_bom_version ]
    runs-on: ${{ needs.determine-runner-integration.outputs.runner }}
    uses: KaleyraVideo/VideoAndroidSDK/.github/workflows/release_notes.yml@main
    with:
      tag: "${{needs.update_sdk_version.outputs.tag}}"
    secrets: inherit

  release_notes:
    needs: [ determine-runner-integration, update_sdk_version, update_bom_version ]
    runs-on: ${{ needs.determine-runner-integration.outputs.runner }}
    uses: KaleyraVideo/VideoAndroidSDK/.github/workflows/release_app.yml@main
    with:
      tag: "${{needs.update_sdk_version.outputs.tag}}"
    secrets: inherit
