name: Create release notes

on:
  workflow_dispatch:
    inputs:
      tag:
        description: Define the tag
        type: string
        required: true
  workflow_call:
    inputs:
      tag:
        description: Define the tag
        type: string
        required: true
jobs:

  determine-runner-integration:
    name: Determine which runner to use for integration tests
    runs-on: ubuntu-latest
    outputs:
      runner: ${{ steps.set-runner.outputs.runner }}
    steps:
      - name: Generate a token
        id: generate_token
        uses: actions/create-github-app-token@v1
        with:
          app-id: ${{ secrets.APP_ID }}
          private-key: ${{ secrets.APP_PRIVATE_KEY }}
      - name: Determine which runner to use
        id: set-runner
        uses: benjaminmichaelis/get-soonest-available-runner@v1.1.0
        with:
          primary-runner: "self-hosted"
          fallback-runner: "ubuntu-latest"
          min-available-runners: 1
          github-token: ${{steps.generate_token.outputs.token}}

  create_release_notes:
    needs: determine-runner-integration
    runs-on: ${{ needs.determine-runner-integration.outputs.runner }}
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0
          fetch-tags: true
          ref: ${{ inputs.tag }}
      - name: set up JDK 17
        uses: actions/setup-java@v4
        with:
          java-version: '17'
          distribution: 'adopt'
          cache: 'gradle'
      - name: Setup Android SDK
        uses: android-actions/setup-android@v3
      - name: Setup Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.10'
          cache: 'pip'
      - name: Install python deps
        run: pip install -r requirements.txt
      - name: Grant execute permission for gradlew
        run: chmod +x gradlew
      - name: Decode Keystore
        id: decode_keystore
        env:
          ENCODED_STRING: ${{ secrets.KEYSTORE }}
        run: echo $ENCODED_STRING | base64 -di > app/keystores/release.keystore
      - name: Generate app apk debug
        run: ./gradlew :app:assembleDebug
      - name: Generate app apk release
        run: ./gradlew :app:assembleRelease
        env:
          SIGNING_KEY_ALIAS: ${{ secrets.SIGNING_KEY_ALIAS }}
          SIGNING_KEY_PASSWORD: ${{ secrets.SIGNING_KEY_PASSWORD }}
          SIGNING_STORE_PASSWORD: ${{ secrets.SIGNING_STORE_PASSWORD }}
      - name: Get commit summary
        id: get_commit_summary
        run: |
            new_tag=${{ inputs.tag }}
            previous_tag=$(git tag --sort=-creatordate | sed -n 2p)
            commit_summary="$(git log --oneline --pretty=tformat:"%h %s" $previous_tag..$new_tag)"
            echo "commit_summary<<EOF"$'\n'"$commit_summary"$'\n'EOF >> $GITHUB_OUTPUT
      - name: Release notes
        uses: softprops/action-gh-release@v2
        with:
          draft: true
          make_latest: 'true'
          tag_name: ${{ inputs.tag }}
          files: |
            app/build/outputs/apk/debug/app-debug.apk
            app/build/outputs/apk/release/app-release.apk
          generate_release_notes: true
