name: Release app on stores

on:
  workflow_dispatch: { }
  push:
    tags:
      - '**'
jobs:
  build_common:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: set up JDK 17
        uses: actions/setup-java@v4
        with:
          java-version: '17'
          distribution: 'adopt'
          cache: 'gradle'
      - name: Setup Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.10'
          cache: 'pip'
      - name: Install python deps
        run: pip install -r requirements.txt
      - name: Grant execute permission for gradlew
        run: chmod +x gradlew
      - name: Decode Keystore
        id: decode_keystore
        uses: timheuer/base64-to-file@v1
        with:
          fileName: 'keystores/release.keystore'
          encodedString: ${{ secrets.KEYSTORE }}
      - name: Build app
        run: ./gradlew :app:build
      - name: Build app bundle release (AAB)
        run: ./gradlew :app:bundleRelease
        env:
          SIGNING_KEY_ALIAS: ${{ secrets.SIGNING_KEY_ALIAS }}
          SIGNING_KEY_PASSWORD: ${{ secrets.SIGNING_KEY_PASSWORD }}
          SIGNING_STORE_PASSWORD: ${{ secrets.SIGNING_STORE_PASSWORD }}
      - name: Deploy to PlayStore
        uses: r0adkll/upload-google-play@v1
        with:
          serviceAccountJsonPlainText: ${{ secrets.GOOGLE_SERVICE_ACCOUNT_JSON }}
          packageName: com.kaleyra.demo_video_sdk
          releaseFiles: app/build/outputs/bundle/release/app-release.aab
          track: beta
          mappingFile: app/build/outputs/mapping/release/mapping.txt
          debugSymbols: app/build/intermediates/merged_native_libs/release/out/lib
      - name: Deploy to Huawei App Gallery
        uses: muhamedzeema/appgallery-deply-action@main
        with:
          client-id: ${{secrets.HUAWEI_CLIENT_ID}}
          client-key: ${{secrets.HUAWEI_CLIENT_KEY}}
          app-id: ${{secrets.HUAWEI_APP_ID}}
          file-extension: "aab"
          file-path: "app/build/outputs/bundle/release/app-release.aab"
          submit: false